### ISSUE TITLE
延迟测试建议

### ISSUE THREAD

**Issue by zhkong** [HMBSbige/ShadowsocksR-Android#11]
十分感谢您继续维护ShadowsocksR-Android这类项目

软件使用中我有个小建议
在测试里有“完整tcp延迟”和”完整http延迟"两个选项
建议采用不同的图标以区分😂

**Comment by luoxh04** [comment]
我也是一开始没明白，后来看延迟不同，大概明白了

**Comment by xicong** [comment]
测试延迟的时候经常会出现第一次提示没显示信息，第二次又正常了
