### ISSUE TITLE
我感觉现在版本问题很大啊

### ISSUE THREAD

**Issue by HMBSbige** [HMBSbige/ShadowsocksR-Android#3]
我看下的人挺多，怎么没人发现？是不是不好用就卸了 (ﾟДﾟ≡ﾟдﾟ)!?

同样的 ACL 原版很快，现在这版本 ACL 列表一大就慢的要死

不知道是什么的锅，有空转成 Kotlin，二进制也自行编译

你们 issue 尽管发，能不能处理就不知道了 (｀・ω・´)

~~反正也是自用的~~

**Comment by ChengzhiLiu** [comment]
我今天晚上试了一下，觉得好像又不是bug，反倒有点像网络问题。原版SSRR、Maying和这个修改版更新ACL的速度基本都是差不多的，甚至三者都有好几次更新错误的提示。今天晚上和昨天好几次原版SSRR（Maying没测）也是更新不了ACL，同时iOS端的Quantumult也是更新不了.conf的路由配置文件，从来没有这么不稳定过，很迷。我估计跟最近GFW的骚操作有关。

**Comment by HMBSbige** [comment]
我说的不是更新ACL啊，是指ACL过大分流就很慢

更新ACL明显是自己网络问题

**Comment by ssrpanel** [comment]
一堆坑，wechat group的G大佬搞的个半死。

**Comment by jorismq** [comment]
平常不用ACL
。。。。话说在服务列表，两个测ping的按键有什么不同？

**Comment by ChengzhiLiu** [comment]
> 平常不用ACL
> 。。。。话说在服务列表，两个测ping的按键有什么不同？

左边TCP延迟，右边HTTP延迟。

**Comment by ChengzhiLiu** [comment]
> 我说的不是更新ACL啊，是指ACL过大分流就很慢
> 
> 更新ACL出错明显是自己网络问题

分流慢的问题我好像也感受到了，有时候不知道是断流还是分流慢，不知是什么原因。是否有计划推出针对此问题的更新？

**Comment by HMBSbige** [comment]
早解决了，等更新吧

**Comment by jorismq** [comment]
https://github.com/HMBSbige/ShadowsocksR-Android/issues/3#issuecomment-541391826

有时候左边的能ping通，右边没速度，不能科学上网
有时候两边都能ping通，但还是不能上网

**Comment by pepsigold** [comment]
大佬赶紧更新了哈哈哈哈谢谢

**Comment by xicong** [comment]
大佬。目前的更新只有github吗？还有其他的渠道吗？
