### ISSUE TITLE
麻烦作者找找原因，看下问题在哪？

### ISSUE THREAD

**Issue by XinSSS** [HMBSbige/ShadowsocksR-Android#38]
原版和你的修改版翻墙都没问题，问题在于使用你的修改版，网络连接测试一直是404

这当然不会是我的使用问题，如果作者确定你的修改版没问题，那是谁的问题？

**Comment by XinSSS** [comment]
录制视频https://mega.nz/#!NJpXQKrR!A66EmbHPok6mp-kWD1eLIPGNoUj-1NEAQ07Hx7F-2-I

**Comment by HMBSbige** [comment]
看了视频猜测是，开了分应用代理且没使用绕行模式，如果你想要在主界面测连接，可以在分应用添加自身。

以后确定有问题可以 Reopen 之前的 issue，不用再开一个

**Comment by XinSSS** [comment]
OK， 3q 解答
