### ISSUE TITLE
更新订阅后节点的排序问题

### ISSUE THREAD

**Issue by 2670135311** [HMBSbige/ShadowsocksR-Android#40]
1.貌似自动更新订阅功能从未生效过，需要手动更新
2.手动更新订阅后，如果添加了新的节点或者节点名称有变动，会被自动放在节点列表的最后，而不是重新排序

手机型号:MI8
安卓10
软件版本3.6.0

**Comment by HMBSbige** [comment]
1. 可能是你自己的问题
2. 已知问题

**Comment by HMBSbige** [comment]
Duplicate of #13
