### ISSUE TITLE
BlueStack蓝叠模拟器使用显示“状态码无效 #404”

### ISSUE THREAD

**Issue by Cartagra** [HMBSbige/ShadowsocksR-Android#6]
![image](https://user-images.githubusercontent.com/20151044/65381534-01c9aa00-dd26-11e9-8037-81a4a16832b2.png)

尝试改了路由为'绕过局域网及中国大陆地址'问题依旧，旧版3.5.4没有出现问题。

**Comment by HMBSbige** [comment]
如果 [3.6.0](https://github.com/HMBSbige/ShadowsocksR-Android/releases/tag/3.6.0) 版本还有这 Bug，你可以 Reopen
