### ISSUE TITLE
大佬，扫描二维码一点击就跳转到其他应用了，麻烦修复一下呗，还有能否考虑在app里面加一个版本更新到功能呀，谢谢

### ISSUE THREAD

**Issue by xicong** [HMBSbige/ShadowsocksR-Android#8]

**Comment by ChengzhiLiu** [comment]
你说的第一个问题能描述得更详细点吗？我这边没有复现你说的这个“bug”。

**Comment by xicong** [comment]
<img width="229" alt="QQ20190925-102730@2x" src="https://user-images.githubusercontent.com/11675597/65564360-3b492200-df7f-11e9-85bf-dfa1147e3d56.png">
<img width="237" alt="QQ20190925-102810@2x" src="https://user-images.githubusercontent.com/11675597/65564367-400dd600-df7f-11e9-8d1c-cb81589704e4.png">

就这里，点击二维码会跳转到火币app里面

录了个视频这里传不了，如果有需要的话麻烦看有啥群不，我直接在群里发给你

**Comment by ChengzhiLiu** [comment]
你确定一下是不是你说的那个火币app的问题。我这边没有安装火币，是可以正常调用应用内扫描器的。

**Comment by xicong** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/11675597/65653053-706c7780-e046-11e9-97ff-605ea7d9e4da.jpeg)
![WechatIMG1](https://user-images.githubusercontent.com/11675597/65653055-72363b00-e046-11e9-98fa-257dc057fed4.jpeg)

大佬，我在旧手机用的时候又发现了一个新问题，测试了很多次，但是我在华为VIE-AL10，和，oppo r9s 上都能正常用

现在解析失败这个手机装之前3.5.4的ssr又是正常的

**Comment by xicong** [comment]
然后上个问题测试了，我把火币app卸载了，扫码就正常了

**Comment by ChengzhiLiu** [comment]
第二个问题我不是很清楚，要等开发者来回答，我猜是最后打包过程的问题，OPPO手机上比较容易有这个问题。

**Comment by HMBSbige** [comment]
6.0不支持v2签名，等下版本吧

**Comment by xicong** [comment]
好的 ，那我等下个版本
